vich_uploader:
    db_driver: orm

    mappings:
        logo_image:
            uri_prefix: /images/logos
            upload_destination: '%kernel.project_dir%/public/images/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
