vich_uploader:
    db_driver: orm

    mappings:
        offre_image:
            uri_prefix: /assets/images/packages
            upload_destination: '%kernel.project_dir%/public/assets/images/packages/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        pays_image:
            uri_prefix: /assets/images/gallary
            upload_destination: '%kernel.project_dir%/public/assets/images/gallary/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
