vich_uploader:
    db_driver: orm

    mappings:
        chambre_image:
            uri_prefix: /images/chambres
            upload_destination: '%kernel.project_dir%/public/images/chambres'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        hotel_image:
            uri_prefix: /images/hotels
            upload_destination: '%kernel.project_dir%/public/images/hotels'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
